
import __ASTRO_IMAGE_IMPORT_2wPMBd from "/src/images/team/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F1.md";
import __ASTRO_IMAGE_IMPORT_mKb6z from "/src/images/customers/2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F1.md";
import __ASTRO_IMAGE_IMPORT_1nYf0w from "/src/images/team/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F3.md";
import __ASTRO_IMAGE_IMPORT_1uFrjX from "/src/images/customers/3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F3.md";
import __ASTRO_IMAGE_IMPORT_O3sHb from "/src/images/team/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F4.md";
import __ASTRO_IMAGE_IMPORT_Z2rAygW from "/src/images/customers/4.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F4.md";
import __ASTRO_IMAGE_IMPORT_f7GoP from "/src/images/team/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F5.md";
import __ASTRO_IMAGE_IMPORT_Z1jFq3V from "/src/images/customers/5.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F5.md";
import __ASTRO_IMAGE_IMPORT_ZjN4Sv from "/src/images/team/6.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F6.md";
import __ASTRO_IMAGE_IMPORT_ZbKhPU from "/src/images/customers/6.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F6.md";
import __ASTRO_IMAGE_IMPORT_ZBYpkj from "/src/images/team/10.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fdavid-lee.md";
import __ASTRO_IMAGE_IMPORT_ZXsGiL from "/src/images/changelog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fchangelog%2F1.md";
import __ASTRO_IMAGE_IMPORT_9rqTf from "/src/images/changelog/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fchangelog%2F2.md";
import __ASTRO_IMAGE_IMPORT_1hmz7g from "/src/images/changelog/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fchangelog%2F3.md";
import __ASTRO_IMAGE_IMPORT_1WU1iR from "/src/images/team/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F2.md";
import __ASTRO_IMAGE_IMPORT_mKj6W from "/src/images/customers/2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F2.md";
import __ASTRO_IMAGE_IMPORT_1fO1Tf from "/src/images/integrations/1.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F1.md";
import __ASTRO_IMAGE_IMPORT_7Nsnm from "/src/images/integrations/2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F2.md";
export default new Map([["/src/images/team/1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F1.md", __ASTRO_IMAGE_IMPORT_2wPMBd], ["/src/images/customers/2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F1.md", __ASTRO_IMAGE_IMPORT_mKb6z], ["/src/images/team/3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F3.md", __ASTRO_IMAGE_IMPORT_1nYf0w], ["/src/images/customers/3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F3.md", __ASTRO_IMAGE_IMPORT_1uFrjX], ["/src/images/team/4.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F4.md", __ASTRO_IMAGE_IMPORT_O3sHb], ["/src/images/customers/4.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F4.md", __ASTRO_IMAGE_IMPORT_Z2rAygW], ["/src/images/team/5.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F5.md", __ASTRO_IMAGE_IMPORT_f7GoP], ["/src/images/customers/5.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F5.md", __ASTRO_IMAGE_IMPORT_Z1jFq3V], ["/src/images/team/6.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F6.md", __ASTRO_IMAGE_IMPORT_ZjN4Sv], ["/src/images/customers/6.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F6.md", __ASTRO_IMAGE_IMPORT_ZbKhPU], ["/src/images/team/10.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fdavid-lee.md", __ASTRO_IMAGE_IMPORT_ZBYpkj], ["/src/images/changelog/1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fchangelog%2F1.md", __ASTRO_IMAGE_IMPORT_ZXsGiL], ["/src/images/changelog/2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fchangelog%2F2.md", __ASTRO_IMAGE_IMPORT_9rqTf], ["/src/images/changelog/3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fchangelog%2F3.md", __ASTRO_IMAGE_IMPORT_1hmz7g], ["/src/images/team/2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F2.md", __ASTRO_IMAGE_IMPORT_1WU1iR], ["/src/images/customers/2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fcustomers%2F2.md", __ASTRO_IMAGE_IMPORT_mKj6W], ["/src/images/integrations/1.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F1.md", __ASTRO_IMAGE_IMPORT_1fO1Tf], ["/src/images/integrations/2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintegrations%2F2.md", __ASTRO_IMAGE_IMPORT_7Nsnm]]);
		